# Generated by Django 4.1.4 on 2022-12-31 09:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models
import employer_profile.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('founded_year', models.DateField(verbose_name='company founded date')),
                ('website_url', models.CharField(max_length=250, verbose_name='company website url')),
                ('logo', models.ImageField(upload_to=employer_profile.models.upload_logo_path, verbose_name='company logo')),
                ('street_address', models.CharField(max_length=150, verbose_name='company location street name')),
                ('city', models.CharField(max_length=100, verbose_name='company city')),
                ('province', models.CharField(max_length=100, verbose_name='province')),
                ('locations', django_mysql.models.ListCharField(models.CharField(max_length=100), max_length=1111, size=10, verbose_name='company office locations')),
                ('cover_page', models.ImageField(upload_to=employer_profile.models.upload_cover_pic, verbose_name='company cover pic')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user id')),
            ],
        ),
    ]
