# Generated by Django 4.1.4 on 2022-12-31 09:28

import applicant_profile.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicantProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=50, verbose_name='Job Level')),
                ('skills', django_mysql.models.ListCharField(models.CharField(max_length=50), max_length=816, size=15, verbose_name='Applicant Skills')),
                ('experience', models.PositiveSmallIntegerField(verbose_name='years of experience')),
                ('date_of_birth', models.DateField(verbose_name='date of birth')),
                ('gender', models.CharField(max_length=25, verbose_name='gender')),
                ('profile_pic', models.ImageField(null=True, upload_to=applicant_profile.models.upload_image_path, verbose_name='profile pic')),
                ('resume', models.FileField(blank=True, null=True, upload_to=applicant_profile.models.upload_path_resume, verbose_name='resume')),
                ('expected_salary', models.IntegerField(verbose_name='expected salary')),
                ('street', models.CharField(max_length=150, verbose_name='street address')),
                ('city', models.CharField(max_length=150, verbose_name='city')),
                ('province', models.CharField(max_length=150, verbose_name='province')),
                ('preferred_job_location', django_mysql.models.ListCharField(models.CharField(max_length=50), max_length=306, size=5, verbose_name='preferred job location')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
    ]
