# Generated by Django 4.1.4 on 2023-01-01 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantprofile',
            name='level',
            field=models.CharField(choices=[('entry Level', 'entry level'), ('mid Level', 'mid level'), ('senior Level', 'senior level'), ('top Level', 'top level')], max_length=50, verbose_name='Job Level'),
        ),
        migrations.AlterField(
            model_name='applicantprofile',
            name='province',
            field=models.CharField(choices=[('lumbini', 'lumbini'), ('madesh', 'madesh'), ('gagmati', 'bagmati'), ('gandaki', 'gandaki'), ('karnali', 'karnali'), ('sudur paschim', 'sudur paschim'), ('province no 1', 'province no 1')], max_length=150, verbose_name='province'),
        ),
    ]
