# Generated by Django 4.1.4 on 2023-01-02 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant_profile', '0003_alter_applicantprofile_province'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantprofile',
            name='level',
            field=models.CharField(choices=[('entry level', 'entry level'), ('mid level', 'mid level'), ('senior level', 'senior level'), ('top level', 'top level')], max_length=50, verbose_name='Job Level'),
        ),
    ]
