# Generated by Django 4.1.4 on 2023-01-01 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='employment_type',
            field=models.CharField(choices=[('full time', 'full time'), ('part time', 'part time'), ('intership', 'intership')], max_length=150, verbose_name='employment type'),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_category',
            field=models.CharField(choices=[('Training & Communication Associate', 'Training & Communication Associate'), ('IT & Telecommunication', 'IT & Telecommunication'), ('Marketing / Advertising / Customer Service', 'Marketing / Advertising / Customer Service'), ('Customer Support', 'Customer Support'), ('Sales / Public Relations', 'Sales / Public Relations'), ('General Mgmt. / Administration / Operations', 'General Mgmt. / Administration / Operations'), ('Teaching / Education', 'Teaching / Education'), ('Journalism / Editor / Media', 'Journalism / Editor / Media'), ('Accounting / Finance', 'Accounting / Finance')], max_length=150, verbose_name='job category'),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_level',
            field=models.CharField(choices=[('entry Level', 'entry level'), ('mid Level', 'mid level'), ('senior Level', 'senior level'), ('top Level', 'top level')], max_length=150, verbose_name='job level'),
        ),
    ]
