# Generated by Django 4.1.4 on 2023-01-02 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_alter_job_employment_type_alter_job_job_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='employment_type',
            field=models.CharField(choices=[('full time', 'full time'), ('part time', 'part time'), ('internship', 'intership')], max_length=150, verbose_name='employment type'),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_level',
            field=models.CharField(choices=[('entry level', 'entry level'), ('mid level', 'mid level'), ('senior level', 'senior level'), ('top level', 'top level')], max_length=150, verbose_name='job level'),
        ),
    ]
